---
from: markdown+emoji
format:
  revealjs:
    logo: images/logo-affiliation.png
    footer: "{{< fa brands github >}} &nbsp;[`biodiversitydata/data-sharing`](https://github.com/biodiversitydata/data-sharing) &nbsp; &bull; &nbsp; {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} &nbsp;[`cc-by-4.0`](https://creativecommons.org/licenses/by/4.0/deed.en)"
    smaller: true
    auto-stretch: false
    chalkboard: true
    toc-depth: 1
    theme: [default, "styles/main.scss"]
engine: knitr
---

<!-- Insert section 'Title slide' -->

```{r}
#| child: "sections/title-slide.qmd"
```


<!-- Insert section 'Table of contents' -->

```{r}
#| child: "sections/table-of-contents.qmd"
```

<!-- Insert section 'Introduction' -->

```{r}
#| child: "sections/introduction.qmd"
```

<!-- Insert section 'Shiny App' -->

```{r}
#| child: "sections/research-compendium.qmd"
```

<!-- Insert section 'R package' -->

```{r}
#| child: "sections/r-package.qmd"
```

<!-- Insert section 'Shiny App' -->

```{r}
#| child: "sections/shiny-app.qmd"
```

<!-- Insert section 'Others' -->

```{r}
#| child: "sections/others.qmd"
```

